// Content data for the CLP Phase 2 build. All copy taken verbatim from
// phase2-content-brief.md (Sections A and B) / the existing homepage.

const SITE = 'https://chooleepartners.com';

/* Postal address, used where a page has to give a contact route in writing. */
const ADDRESS = {
  firm: 'Messrs Choo, Lee &amp; Partners',
  lines: ['D4-U5-1, Solaris Dutamas', 'No. 1, Jalan Dutamas 1', '50480 Kuala Lumpur, Malaysia'],
};

const partners = [
  {
    slug: 'choo-tzu-hao',
    name: 'Choo Tzu Hao',
    role: 'Partner &middot; Corporate &amp; Commercial',
    photo: 'partner-choo-tzu-hao.jpg',
    title: 'Choo Tzu Hao &mdash; Corporate &amp; Commercial Partner | Choo, Lee &amp; Partners',
    meta: "Choo Tzu Hao leads CLP's corporate and commercial transaction practice: structuring, shareholders' arrangements, M&amp;A and commercial contracts.",
    lede: "Partner leading the Firm's corporate and commercial transaction practice.",
    focus: "Corporate structuring, shareholders' arrangements, M&amp;A and transaction advisory.",
    practices: ['corporate-commercial', 'employment-hr', 'data-protection-pdpa', 'ip-technology'],
    bio: [
      ['Qualifications and admission',
        'Tzu Hao obtained his LLB (Honours) from Queen&rsquo;s University Belfast in 2017. He read in Messrs Valen, Oh &amp; Partners before being admitted to the Malaysian Bar on 12 October 2020.'],
      ['Practice',
        "Tzu Hao leads the Firm's corporate and commercial transaction practice. His work focuses on corporate structuring, shareholders' arrangements, business transactions, joint ventures, investment documentation, commercial contracts and transaction advisory for companies, business owners, founders, investors and commercial operators. He regularly advises on shareholders' agreements, founders' agreements, joint venture agreements, investment agreements, share, business and asset sale agreements, corporate restructuring, board and shareholders' approvals, governance arrangements and commercial deal structuring. His commercial documentation work includes distribution, supply, agency, franchise and licensing arrangements, project and service agreements, guarantees, term sheets, MOUs and NDAs."],
      ['Approach',
        "His practice is transaction-focused and commercially driven: identifying the correct legal structure, aligning documents with the parties' commercial bargain, managing negotiation points clearly, and ensuring documentation supports practical execution."],
    ],
  },
  {
    slug: 'lee-lih-ching',
    name: 'Lee Lih Ching',
    role: 'Partner &middot; Conveyancing, Banking &amp; Real Estate',
    photo: 'partner-lee-lih-ching.jpg',
    title: 'Lee Lih Ching &mdash; Conveyancing &amp; Real Estate Partner | Choo, Lee &amp; Partners',
    meta: "Lee Lih Ching leads CLP's conveyancing and real estate practice: property transactions, financing documentation and completion matters.",
    lede: "Partner leading the Firm's conveyancing and real estate transaction practice.",
    focus: 'Property transactions, financing documentation and completion matters.',
    practices: ['conveyancing-property'],
    bio: [
      ['Qualifications and admission',
        'Lih Ching graduated with LLB (Honours) from Queen&rsquo;s University Belfast in 2017 and obtained the Certificate of Legal Practice in 2018. She was called to the Malaysian Bar on 12 December 2019.'],
      ['Practice',
        'Lih Ching leads the Firm&rsquo;s conveyancing and real estate transaction practice, acting for individual purchasers, vendors, developers, corporate clients and financial institutions. She advises and acts in developer sales, sub-sale transactions, perfection of transfer and charge, discharge of charge, redemption matters, leases and tenancies. Her practice also covers transmission and transfer of property arising from estate administration, and banking and financing documentation connected with real estate transactions, including loan agreements, charges, guarantees, security documents, bridging finance and end-financing.'],
      ['Approach',
        'Her practice is completion-focused: title review, transaction structure, consent requirements, stamping, adjudication, financing conditions, redemption and completion timelines, handled with proper documentation control and fewer avoidable delays.'],
    ],
  },
  {
    slug: 'tsu-jean-yinn',
    name: 'Tsu Jean Yinn (Jean)',
    role: 'Partner &middot; Litigation &amp; Dispute Resolution',
    photo: 'partner-tsu-jean-yinn.jpg',
    title: 'Tsu Jean Yinn (Jean) &mdash; Litigation Partner | Choo, Lee &amp; Partners',
    meta: "Jean leads CLP's litigation and dispute resolution practice: civil and commercial disputes, debt recovery and contentious estates.",
    lede: "Partner leading the Firm's litigation and dispute resolution practice.",
    focus: 'Civil and commercial disputes, debt recovery and contentious estates.',
    practices: ['dispute-resolution'],
    bio: [
      ['Qualifications and admission',
        'Jean graduated from the University of Liverpool in 2013 and obtained her Certificate of Legal Practice in 2016. She was called to the Malaysian Bar in 2018.'],
      ['Practice',
        'Jean leads the Firm&rsquo;s litigation and dispute resolution practice, focusing on civil and commercial disputes, contentious estate and probate matters, debt recovery, property disputes, contractual claims, and partnership and shareholder conflicts. She represents individuals, business owners, companies and private clients in disputes involving contractual obligations, unpaid sums, business arrangements, estate administration, property ownership, tenancy issues, defamation, enforcement of rights and settlement negotiations. Her litigation work includes pleadings, applications, affidavits, cause papers, submissions and interlocutory matters including injunctions, summary judgment, discovery, striking out and enforcement proceedings.'],
      ['Approach',
        'Her practice is dispute-focused and strategy-driven: early case assessment, evidence review, procedural planning, settlement positioning and clear litigation strategy.'],
    ],
  },
  {
    slug: 'ku-yee-hui',
    name: 'Ku Yee Hui (Amanda)',
    role: 'Partner &middot; Estate Planning &amp; Private Client',
    photo: 'partner-ku-yee-hui.jpg',
    title: 'Ku Yee Hui (Amanda) &mdash; Estate Planning Partner | Choo, Lee &amp; Partners',
    meta: "Amanda leads CLP's estate planning and private client practice: wills, trusts, probate, letters of administration and succession planning.",
    lede: "Partner leading the Firm's estate planning and private client practice.",
    focus: 'Wills, trusts, probate and succession planning for families and business owners.',
    practices: ['estate-planning-private-client'],
    bio: [
      ['Qualifications and admission',
        'Amanda graduated with LLB (Honours) from the University of Liverpool in 2019. She was called to the Bar of England and Wales in 2021 and was subsequently admitted to the Malaysian Bar in 2022.'],
      ['Practice',
        'Amanda leads the Firm&rsquo;s estate planning and private client practice, focusing on wills, probate, letters of administration, trust-related documentation, family asset arrangements, estate administration and succession-related advisory for individuals, families, business owners and private clients. She advises on structuring and documenting estate planning arrangements &mdash; wills, trust deeds, powers of attorney, asset distribution arrangements and documents relating to executors, administrators, trustees and beneficiaries &mdash; as well as estate administration matters including grant applications, extraction of grants and distribution steps.'],
      ['Approach',
        "Her practice is private-client focused and detail-driven: understanding the client's family structure, asset position, intended distribution and future administration issues, so documents are clear, workable and implementable."],
    ],
  },
  {
    slug: 'tung-zhen-yuan',
    name: 'Tung Zhen Yuan (Ken)',
    role: 'Partner &middot; Criminal Practice',
    photo: 'partner-tung-zhen-yuan.jpg',
    title: 'Tung Zhen Yuan (Ken) &mdash; Criminal Practice Partner | Choo, Lee &amp; Partners',
    meta: "Ken leads CLP's criminal practice: police investigations, remand and bail, AMLA matters, mitigation and criminal trials.",
    lede: "Partner leading the Firm's criminal practice.",
    focus: 'Criminal litigation, AMLA-related matters and urgent enforcement advisory.',
    practices: ['criminal-practice'],
    bio: [
      ['Qualifications and admission',
        'Ken graduated with a Bachelor of Laws from Queen&rsquo;s University Belfast in 2021. He completed the Bar Training Course together with a Master of Laws from Cardiff University, and was admitted to the Bar of England and Wales as a member of The Honourable Society of Lincoln&rsquo;s Inn in 2022.'],
      ['Practice',
        'Ken leads the Firm&rsquo;s criminal practice, covering criminal litigation, enforcement matters and urgent criminal advisory work: police investigations, remand and bail proceedings, criminal charges, mitigation, trial preparation and related court proceedings. He advises individuals, business owners, directors and corporate clients in matters involving the Penal Code, Criminal Procedure Code, Kidnapping Act, AMLA 2001, MACC Act 2009, fraud, criminal breach of trust, cheating, financial crime and regulatory offences. He has particular experience in AMLA-related matters, including account freezing, seizure issues, suspected mule-account allegations, banking restrictions and account closure issues.'],
      ['Approach',
        'His practice is practical, discreet and response-driven: early case assessment, preserving documents and evidence, managing urgent procedural steps carefully, and clear advice at each stage.'],
    ],
  },
];

const practices = [
  {
    slug: 'corporate-commercial',
    name: 'Corporate &amp; Commercial',
    title: 'Corporate &amp; Commercial Lawyers in Kuala Lumpur | Choo, Lee &amp; Partners',
    meta: "Partner-led corporate and commercial advice in Malaysia: shareholders' agreements, joint ventures, M&amp;A, fundraising and commercial contracts.",
    lede: 'Corporate structuring, business transactions and the contracts that keep a business running.',
    blurb: "Shareholders' and founders' arrangements, joint ventures, M&amp;A and fundraising, corporate restructuring, commercial contracts, distribution and supply, NDAs and deal structuring.",
    lead: 'choo-tzu-hao',
    intro: [
      "CLP advises companies, founders, investors and commercial operators on corporate structuring, business transactions and the contracts that keep a business running. The practice is transaction-focused and commercially driven: we identify the correct legal structure, align documents with the parties' commercial bargain, and ensure documentation supports practical execution.",
    ],
    help: [
      "Shareholders', founders' and joint venture agreements",
      'Mergers, acquisitions and fundraising: due diligence, share/business/asset sales, term sheets, share subscription, preference shares, convertible loans',
      'Corporate restructuring, board and shareholders&rsquo; approvals, governance',
      'Commercial contracts: distribution, supply, agency, sponsorship, franchising and licensing, service agreements, guarantees, NDAs, MOUs, novation and assignment',
    ],
    experience: 'Business acquisitions; shareholder and investor arrangements; joint venture structures; private company investment documentation; restaurant and F&amp;B expansion structures; commercial supply and distribution arrangements; franchising and licensing frameworks; transaction documents involving staged payments, conditions precedent, completion mechanics and post-completion obligations.',
  },
  {
    slug: 'conveyancing-property',
    name: 'Conveyancing &amp; Real Estate',
    title: 'Conveyancing &amp; Real Estate Lawyers in Kuala Lumpur | Choo, Lee &amp; Partners',
    meta: 'Malaysian conveyancing and property lawyers: sale and purchase, sub-sales, perfection of transfer and charge, tenancies and property financing.',
    lede: 'Property transactions, land dealings, financing documentation and completion matters.',
    blurb: 'Developer sales and sub-sales, perfection of transfer and charge, discharge and redemption, leases and tenancies, estate transmissions, and loan and security documentation.',
    lead: 'lee-lih-ching',
    intro: [
      'CLP handles property transactions, land dealings, financing documentation and completion matters for individual purchasers, vendors, developers, corporate clients and financial institutions. The practice is completion-focused, with emphasis on title review, transaction structure, consent requirements, stamping, adjudication, financing conditions and completion timelines.',
    ],
    help: [
      'Developer sales and sub-sale transactions (residential, commercial, industrial)',
      'Perfection of transfer and perfection of charge; discharge of charge, redemption and refinancing',
      'Leases, tenancies and other property-related instruments',
      "Transmission and transfer of estate properties: probate, letters of administration, beneficiaries' entitlement, assent, transfers by personal representatives",
      'Banking and financing documentation: loan agreements, charges, guarantees, security documents, bridging and end-financing',
    ],
    experience: 'Sub-sale transactions across residential, commercial and industrial properties; developer sale and purchase; perfection matters; redemption and refinancing; estate property transfers involving beneficiaries and family arrangements; commercial tenancies; loan and security documentation connected with property financing.',
  },
  {
    slug: 'dispute-resolution',
    name: 'Dispute Resolution',
    title: 'Dispute Resolution &amp; Litigation Lawyers in Kuala Lumpur | Choo, Lee &amp; Partners',
    meta: 'Civil and commercial litigation in Malaysia: debt recovery, contractual and shareholder disputes, contentious probate, injunctions and settlements.',
    lede: 'Court-driven matters for individuals, business owners, companies and private clients.',
    blurb: 'Civil and commercial litigation, debt recovery, contractual and shareholder disputes, contentious probate, defamation, injunctions and negotiated settlements.',
    lead: 'tsu-jean-yinn',
    intro: [
      'CLP represents individuals, business owners, companies and private clients in court-driven matters. The practice is dispute-focused and strategy-driven, with emphasis on early case assessment, evidence review, procedural planning and settlement positioning &mdash; so clients understand both the strength of their case and the practical risks of pursuing or defending a claim.',
    ],
    help: [
      'Debt recovery, letters of demand, bankruptcy and winding-up related matters',
      'Contractual claims and civil/commercial litigation',
      'Partnership and shareholder disputes',
      'Contentious estate and probate matters; property and tenancy disputes',
      'Defamation claims',
      'Interim and procedural applications: injunctions, summary judgment, discovery, striking out, enforcement proceedings',
      'Settlement proposals and negotiated settlements',
    ],
    experience: 'Debt recovery proceedings; contractual disputes; contested probate and estate disputes; property and tenancy disputes; partnership and shareholder disputes; defamation claims; bankruptcy and winding-up related matters; injunction and summary judgment applications; negotiated settlements.',
  },
  {
    slug: 'employment-hr',
    name: 'Employment &amp; HR',
    title: 'Employment &amp; HR Lawyers in Malaysia | Choo, Lee &amp; Partners',
    meta: 'Employment law advice for Malaysian businesses: employment agreements, contractor arrangements, handbooks, ESOS and compliance.',
    lede: 'Documentation and advisory work that keeps a workforce properly structured.',
    blurb: 'Employment agreements, handbooks, ESOS, advisory and compliance.',
    lead: 'choo-tzu-hao',
    intro: [
      'CLP advises employers on the documentation and day-to-day advisory work that keeps a workforce properly structured &mdash; prepared with enforceability, implementation and commercial reality in mind.',
    ],
    help: [
      'Employment agreements and independent contractor arrangements',
      'Secondment and consultancy arrangements',
      'Employee handbooks and workplace policies',
      'Employee share option schemes (ESOS)',
      'Employment advisory and compliance',
    ],
    experience: null,
  },
  {
    slug: 'data-protection-pdpa',
    name: 'Data Protection &amp; PDPA',
    title: 'PDPA &amp; Data Protection Lawyers in Malaysia | Choo, Lee &amp; Partners',
    meta: 'Personal Data Protection Act 2010 compliance for Malaysian businesses: privacy notices, policies, website terms and data-handling documentation.',
    lede: 'Privacy and data-protection documentation under the Personal Data Protection Act 2010.',
    blurb: 'Privacy notices, PDPA compliance, website terms and policies.',
    lead: 'choo-tzu-hao',
    note: 'Firm to review this page&rsquo;s scope description before launch (per the Phase 2 brief).',
    intro: [
      'CLP prepares the privacy and data-protection documentation Malaysian businesses need under the Personal Data Protection Act 2010, aligned with how the business actually collects and uses personal data.',
    ],
    help: [
      'Privacy notices and PDPA-compliance documentation',
      'Website and app terms of use, terms of service and privacy policies',
      'Data-handling clauses in commercial and employment documentation',
      'PDPA-related advisory for day-to-day operations',
    ],
    experience: null,
  },
  {
    slug: 'ip-technology',
    name: 'Intellectual Property &amp; Technology',
    title: 'IP &amp; Technology Lawyers in Malaysia | Choo, Lee &amp; Partners',
    meta: 'Intellectual property and technology documentation in Malaysia: licensing, franchising, trademark registration and website/app terms.',
    lede: 'Confidentiality, licensing and technology documentation for a business&rsquo;s intangible assets.',
    blurb: 'Licensing, franchising, trademarks and technology documentation.',
    lead: 'choo-tzu-hao',
    intro: [
      "CLP handles the confidentiality, licensing and technology-related documentation that protects and commercialises a business's intangible assets.",
    ],
    help: [
      'Confidentiality, licensing and assignment arrangements',
      'Franchising frameworks',
      'Trademark registration',
      'Website/app terms, terms of use and service, and privacy policies',
    ],
    experience: null,
  },
  {
    slug: 'estate-planning-private-client',
    name: 'Estate Planning, Probate &amp; Private Client',
    title: 'Wills, Trusts &amp; Probate Lawyers in Kuala Lumpur | Choo, Lee &amp; Partners',
    meta: 'Estate planning and private client lawyers in Malaysia: wills, trusts, powers of attorney, probate, letters of administration and succession planning.',
    lede: 'Structuring and documenting estate planning for individuals, families and business owners.',
    blurb: 'Wills, trusts, probate, letters of administration and succession.',
    lead: 'ku-yee-hui',
    intro: [
      "CLP's private client practice helps individuals, families and business owners structure and document their estate planning &mdash; with emphasis on the client's family structure, asset position, intended distribution and future administration, so documents are clear, workable and capable of being implemented when required.",
    ],
    help: [
      'Wills, trust deeds and powers of attorney',
      'Asset distribution arrangements; executor, administrator, trustee and beneficiary documentation',
      'Grant of probate and letters of administration; extraction of grants',
      "Estate administration and distribution; beneficiaries' entitlement",
      'Pre/post-nuptial agreements and joint petition divorce',
      'Succession planning for personal, family and business assets',
    ],
    experience: null,
  },
  {
    slug: 'criminal-practice',
    name: 'Criminal Practice',
    title: 'Criminal Defence Lawyers in Kuala Lumpur | Choo, Lee &amp; Partners',
    meta: 'Criminal practice in Malaysia: police investigations, remand and bail, AMLA matters, account freezing, mitigation and criminal trials.',
    lede: 'Criminal litigation, enforcement matters and urgent criminal advisory work.',
    blurb: 'Investigation-stage support, bail, AMLA matters and criminal trials.',
    lead: 'tung-zhen-yuan',
    intro: [
      "CLP's criminal practice covers criminal litigation, enforcement matters and urgent criminal advisory work. The practice is practical, discreet and response-driven, with emphasis on early case assessment, preserving documents and evidence, and clear advice on the client's options at each stage.",
    ],
    help: [
      'Investigation-stage support, statement advisory and liaison with investigating officers',
      'Remand and bail applications',
      'Matters involving the Penal Code, Criminal Procedure Code, Kidnapping Act, AMLA 2001 and MACC Act 2009',
      'AMLA-related matters: account freezing, seizure issues, suspected mule-account allegations, banking restrictions and account closures',
      'Scam and financial fraud complaints; NSRC / police / bank follow-ups',
      'Plea and mitigation, criminal trials, appeals and revisions, regulatory offence matters',
    ],
    experience: null,
  },
];

module.exports = { SITE, ADDRESS, partners, practices };
